FROM python:3.12-slim
# 2. OS Packages को Latest Version में Upgrade करें (libacl1, libattr1, openssl, ncurses, etc.)
RUN apt-get update && apt-get upgrade -y && apt-get clean

#create non-root user
RUN adduser --disabled-password --no-create-home appuser

WORKDIR /app

# Dependencies Install करें
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# App Code Copy करें
COPY app.py .

#switch on non-root user
USER appuser

# 5000 Port पर सुनेगा
EXPOSE 5000

# App Start करें
CMD ["python", "app.py"]