FROM python:3.9-slim

WORKDIR /app

# Dependencies Install करें
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# App Code Copy करें
COPY app.py .

# 5000 Port पर सुनेगा
EXPOSE 5000

# App Start करें
CMD ["python", "app.py"]